UBUNTU: SAUCE: Revert "bpf: Selftests build error in sockmap_basic.c"
BugLink: https://bugs.launchpad.net/bugs/1871613

This reverts commit f423709649e5743b1a0f21941deecb41230fff3d which is
commit f2e97dc126b712c0d21219ed0c42710006c1cf52 upstream.

This commit has been backported to eoan/linux from v5.4.23 upstream
stable, however due to missing dependencies prog_tests/sockmap_basic.c
can't be compiled:

prog_tests/sockmap_basic.c: In function 'connected_socket_v4':
prog_tests/sockmap_basic.c:22:6: warning: implicit declaration of function 'CHECK_FAIL' [-Wimplicit-function-declaration]
   22 | if (CHECK_FAIL(s == -1))
      | ^~~~~~~~~~
prog_tests/sockmap_basic.c:26:22: error: 'SOL_TCP' undeclared (first use in this function); did you mean 'SOL_TIPC'?
   26 | err = setsockopt(s, SOL_TCP, TCP_REPAIR, &repair, sizeof(repair));
      | ^~~~~~~
      | SOL_TIPC
prog_tests/sockmap_basic.c:26:22: note: each undeclared identifier is reported only once for each function it appears in
prog_tests/sockmap_basic.c: In function 'test_sockmap_basic':
prog_tests/sockmap_basic.c:75:6: warning: implicit declaration of function 'test__start_subtest' [-Wimplicit-function-declaration]
   75 | if (test__start_subtest("sockmap create_update_free"))
      | ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Kleber Sacilotto de Souza <kleber.souza@canonical.com>
Acked-by: Stefan Bader <stefan.bader@canonical.com>
Acked-by: Colin King <colin.king@canonical.com>
Signed-off-by: Stefan Bader <stefan.bader@canonical.com>