UBUNTU: SAUCE: Revert "selftests/bpf: Test freeing sockmap/sockhash with a socket in it"
BugLink: https://bugs.launchpad.net/bugs/1871613

This reverts commit 7c57edd8018e70b4faebf0569a1fa3f35a21829c which is
commit 5d3919a953c3c96c02fc7a337f8376cde43ae31f upstream.

This commit has been backported to eoan/linux from v5.4.20 upstream
stable, however due to missing dependencies prog_tests/sockmap_basic.
can't be compiled:

prog_tests/sockmap_basic.c: In function 'connected_socket_v4':
prog_tests/sockmap_basic.c:22:6: warning: implicit declaration of function 'CHECK_FAIL' [-Wimplicit-function-declaration]
   22 | if (CHECK_FAIL(s == -1))
      | ^~~~~~~~~~
prog_tests/sockmap_basic.c:26:22: error: 'SOL_TCP' undeclared (first use in this function); did you mean 'SOL_TIPC'?
   26 | err = setsockopt(s, SOL_TCP, TCP_REPAIR, &repair, sizeof(repair));
      | ^~~~~~~
      | SOL_TIPC
prog_tests/sockmap_basic.c:26:22: note: each undeclared identifier is reported only once for each function it appears in
prog_tests/sockmap_basic.c: In function 'test_sockmap_basic':
prog_tests/sockmap_basic.c:75:6: warning: implicit declaration of function 'test__start_subtest' [-Wimplicit-function-declaration]
   75 | if (test__start_subtest("sockmap create_update_free"))
      | ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Kleber Sacilotto de Souza <kleber.souza@canonical.com>
Acked-by: Stefan Bader <stefan.bader@canonical.com>
Acked-by: Colin King <colin.king@canonical.com>
Signed-off-by: Stefan Bader <stefan.bader@canonical.com>